Added Semantic Segmentation and Style Transfer
riteshcanfly/InteriorAI pull request #1
Opened 2023-06-27 10:28 UTC by Atithi14

Implementation of Semantic segmentation using the Keras model and applying for class-based style transfer.

- Used VGG_UNET model for semantic segmentation.
- Used a pre-trained model for neural style transfer.
- Implemented Class based style transfer.

2023-07-03 12:04 UTC, RahulJana requested changes
Please fix these.

2023-07-11 05:13 UTC, RahulJana approved these changes

2025-12-06 18:41 UTC, merged

2026-01-08 04:55 UTC, riteshcanfly commented
ok

2026-01-08 04:55 UTC, riteshcanfly commented
deleted